
# server配置
server:
  port: 8080
  servlet:
    context-path: /

# 连接池配置
spring:
  application:
    name: springfox-swagger
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql:///clockin_dev
      username: root
      password: liulove02
      driver-class-name: com.mysql.cj.jdbc.Driver
# mybatis-plus的配置
mybatis-plus:
  type-aliases-package: com.jszx.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDeleted  #全局逻辑删除
      id-type: auto #主键策略自增长
      table-prefix: t_ # 设置表的前缀
#jwt配置
jwt:
  token:
    tokenExpiration: 120 #有效时间,单位分钟
    tokenSignKey: jszx123456  #当前程序签名秘钥 自定义
#springdoc-openapi项目配置，访问地址：http://127.0.0.1:8080/doc.html
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: '技术中心签到系统'
      paths-to-match: '/**'
      packages-to-scan: com.jszx.controller

knife4j:
  enable: true
  setting:
    language: zh-CN
  # 聚合swagger文档
  gateway:
    enable: true

# Logger Config
logging:
  level:
    com.hexadecimal: debug